addSbtPlugin("org.jetbrains" % "sbt-idea-plugin" % "3.18.2")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.1")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.14.2")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.1.0")
addSbtPlugin("nl.gn0s1s" % "sbt-dotenv" % "3.0.0")