name: Publish Plugin

on:
  push:
    tags: [v*.*.*]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IJ_PLUGIN_REPO_TOKEN: ${{ secrets.IJ_PLUGIN_REPO_TOKEN }}
#  JDK_JAVA_OPTIONS: -Xmx16g -Xms16g

jobs:
  build:
    name: Publish
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [temurin@17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java (temurin@11)
        if: matrix.java == 'temurin@11'
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Java (temurin@17)
        if: matrix.java == 'temurin@17'
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Verify plugin compatibility
        run: |
          sbt runPluginVerifier || echo "Plugin verifier done, result ignored"

      - name: Package plugin && kernel
        run: |
          sbt 'packageArtifactZip; project kernel; assembly'
          cp scaleda-kernel/target/scala-2.13/scaleda-kernel.jar target/scaleda-kernel.jar

      - name: Upload binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.{zip,jar}
          file_glob: true
          tag: ${{ github.ref }}


      - name: Publish this plugin
        run: sbt publishPlugin || echo "Plugin publish done, result ignored"
