name: Pages

on:
  push:
    branches:
      - sphinx

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ temurin@17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Generate Sphinx
        run: |
          python3 -m pip install -r docs/requirements.txt
          make -C docs html
      - name: Setup Java (temurin@11)
        if: matrix.java == 'temurin@11'
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Java (temurin@17)
        if: matrix.java == 'temurin@17'
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Generate Scaladoc
        run: |
          sbt 'project kernel; doc' || echo "generate kernel api done"
          sbt doc || echo "generate idea api done"
      - name: Copy Scaladoc to static deploy files
        run: |
          mkdir -p ./docs/_build/html/
          mv ./scaleda-kernel/target/scala-2.13/api ./docs/_build/html/api-kernel && echo "move generated kernel files"
          mv ./target/scala-2.13/api ./docs/_build/html/api-idea && echo "move generated files"
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/_build/html/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2